set encoding=utf-8
set nocompatible
set backspace=indent,eol,start
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set history=50
set ruler
set showcmd
set wrap
set sidescroll=10                           " scroll with 10 characters side offset
set incsearch
set so=5                                    " provides a gap while scrolling
set autowrite
set number                                  " sets the line number
set relativenumber                          " sets the relative line number
set nocp                                    " omnicpp installation

" Set no backup or swapfile
set nobackup
set noswapfile

" set option& sets the default value
if has("vms")
    set nobackup
" else
"     set backup
"     set backupext=.bak                      " sets the default backup extension
    " set backupdir=.bak                      " sets the default backup directory
endif
" set patchmode=.orig                         " keeps the original file
" autocmd Filetype text setlocal textwidth=20

filetype plugin on
filetype indent on

" syntax options
set t_Co=256
set background=light
syntax enable
" syntax clear - disable syntax highlighting for a moment
" syntax off - disable syntax highlighting permanently
colorscheme vitamins
set cursorline
hi CursorLine cterm=bold ctermbg=234

" configure tags - add additional tags here or comment out not-used ones
set tags+=~/.vim/tags/cpp
set tags+=~/.vim/tags/gl
set tags+=~/.vim/tags/sdl
set tags+=~/.vim/tags/qt4
" build tags of your own project with Ctrl-F12
map <C-F12> :!ctags -R --sort=yes --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview

au BufRead *.php set ft=php.html
au BufNewFile *.php set ft=php.html

" NERDTree snippets ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
" let g:NERDTreeWinPos = "right"

" Editor ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
set tw=0
set clipboard=unnamed

" Session in vim -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
" Save session on quitting Vim
" autocmd VimLeave * NERDTreeClose
" autocmd VimLeave * mksession! [filename]

" Restore session on starting Vim
" autocmd VimEnter * call MySessionRestoreFunction()
" autocmd VimEnter * NERDTree

" Windows -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
autocmd BufEnter * silent! lcd %:p:h
noremap ;a 10<c-w><c-w>
noremap ;1  1<c-w><c-w>
noremap ;2  2<c-w><c-w>
noremap ;3  3<c-w><c-w>
noremap ;4  4<c-w><c-w>
noremap ;5  5<c-w><c-w>
noremap ;6  6<c-w><c-w>
noremap ;7  7<c-w><c-w>
noremap ;8  8<c-w><c-w>
noremap ;9  9<c-w><c-w>

" Backup and original file -------------------------------------------------------------------------------------------------------------------------------------------------------------
" set backupdir=./.backup/

" execute pathogen#infect()

" Set filetype tab spaces
autocmd Filetype html,css,xml :setlocal sw=2 ts=2 sts=2
au BufNewFile,BufRead *.jade set filetype=html
autocmd BufRead,BufNewFile *.jade setlocal ft=jade
au BufRead,BufNewFile *.fish set filetype=fish

" Autosave CSS file
" autocmd  TextChanged,TextChangedI <buffer> silent write

" Vim indent guides
" let g:indent_guides_auto_colors = 0
" autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=233
" autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=234
" autocmd BufReadPre,FileReadPre * :IndentGuidesEnable

" Indent Line plugin
let g:indentLine_enabled = 1
let g:indentLine_color_term = 237
" let g:indentLine_char = 'c'

" Python folding
set foldmethod=indent
set foldnestmax=2
noremap <Space> za
noremap <NUL> zR

" File manipulation
noremap tt  :tab split<CR>

" Emmet mapping
let g:user_emmet_expandabbr_key = '<C-X>'
let g:user_emmet_togglecomment_key = '<C-C>'

" Vim vertical line at 80
au Filetype python set colorcolumn=80
highlight ColorColumn ctermbg=234
" guibg=234

" For vim-airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
set laststatus=2
let g:airline_theme="hogan"
" let Powerline_symbols='fancy'
" set font=Inconsolata\ for\ Powerline

" CtrlP settings
let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'

call plug#begin('~/.vim/plugged')
    Plug 'Chiel92/vim-autoformat'
    Plug 'editorconfig/editorconfig-vim'
    Plug 'vim-airline/vim-airline'
    Plug 'nathanaelkane/vim-indent-guides'
    Plug 'mattn/emmet-vim'
    Plug 'vim-airline/vim-airline-themes'
    " Plug ''
call plug#end()
